### ISSUE TITLE
Issue with qGaussian in pysixtrack

### ISSUE THREAD

**Issue by giadarol** [xsuite/xfields#6]
[This](https://github.com/SixTrack/pysixtrack/blob/37e87fab3271e567e4e2c0a2ae6a6980a0dd90b9/pysixtrack/be_beamfields/qgauss.py#L21) does not look correct to me:

```python
    @staticmethod
    def sqrt_beta(sigma, mathlib=MathlibDefault):
        assert sigma > 0
        return 1 / (mathlib.sqrt(2) * sigma)
```

From wikipedia:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/8049893/114299766-62156d80-9abd-11eb-86bc-265adcfbed3b.png">

**Comment by martinschwinzerl** [comment]
Sorry for only responding now, I wasn't aware of this issue. My understanding when writing this (please correct me if I'm wrong) was that \beta is a parameter of the distribution, like \sigma for the Gaussian case i.e., it can be freely varied (within some limits, depending on q). The formula for the variance you referred to gives (AFAIK) the value for 

![image](https://user-images.githubusercontent.com/35835665/126600133-05f8e9cc-3c72-432f-985f-79bca56d29a8.png)

for a random variable x whose values are distributed according to a q-Gaussian distribution.

The method from `pysixtrack` in question calculates a value for \sqrt{\beta} from the corresponding value of \sigma for the Gaussian so that for q = 1, both distributions give the same probability density function. I arrived at the formula by comparing

![image](https://user-images.githubusercontent.com/35835665/126599343-e9418b4e-7290-4f01-9cdf-21f7f2bbce3c.png)

with 

![image](https://user-images.githubusercontent.com/35835665/126599482-fcf3708d-4d70-496b-9cc9-bfc335cda2f3.png) .

For q = 1, C_q = \sqrt{\pi}, equating

![image](https://user-images.githubusercontent.com/35835665/126599689-58717a43-afde-46e6-85e4-70d7582fcbef.png)

gives the same PDF (silently equating the e_q(x) with e(x) in the limit q -> 1). In `SixTrackLib`, this method is called `Math_q_gauss_sqrt_beta_from_gauss_sigma` which requires a lot more typing than the `pysixtrack` name but tries to be explicit about the context.

Please let me know if there is indeed a problem, we should then also fix it for `SixTrackLib`

**Comment by giadarol** [comment]
Hi Martin, for me the problem is that with this convention sigma is not anymore the standard deviation of the distribution for beta != 0

**Comment by giadarol** [comment]
It can be misleading since [here](https://github.com/SixTrack/pysixtrack/blob/37e87fab3271e567e4e2c0a2ae6a6980a0dd90b9/pysixtrack/be_beamfields/spacecharge.py#L61) we explicitly call sigma "bunch length_rms"
